[package]
name = "hyperscan-sys"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

build = "build.rs"

[features]
vectorscan = ["cmake"]

[build-dependencies]
bindgen = "0.73.2"
cmake = { version = "0.1.58", optional = true }
