repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ".*\\.md"
      - id: end-of-file-fixer
        exclude: "CHANGELOG.md|changelog.d/.*"
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: "CHANGELOG.md|changelog.d/.*"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Check black

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.267"
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy

  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.2
    hooks:
      - id: pydocstringformatter

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args: ["--no-default-features", "--", "-D", "warnings"]

  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
