coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
