FROM quay.io/pypa/musllinux_1_1_x86_64:latest AS ragel

WORKDIR /usr/src/colm
RUN curl -fsSL https://github.com/adrian-thurston/colm-suite/archive/refs/tags/colm-0.14.7.tar.gz | tar -xz --strip-components 1 \
    && ./autogen.sh \
    && ./configure --disable-manual \
    && make MAKEFLAGS=-j$(cat /proc/cpuinfo | grep processor | wc -l) \
    && make DESTDIR=/build install \
    && make install

WORKDIR /usr/src/ragel
RUN curl -fsSL https://github.com/adrian-thurston/ragel/archive/refs/tags/7.0.4.tar.gz | tar -xz --strip-components 1 \
    && ./autogen.sh \
    && ./configure --disable-manual --with-colm=/usr/local \
    && make MAKEFLAGS=-j$(cat /proc/cpuinfo | grep processor | wc -l) \
    && make DESTDIR=/build install

FROM quay.io/pypa/musllinux_1_1_x86_64:latest

COPY --from=ragel /build/ /

# vectorscan's fat-runtime build_wrapper.sh needs GNU mktemp and a libc.so.6 to read libc symbols from
RUN apk add boost-dev clang-libs coreutils \
    && ln -s "$(readlink -f /usr/lib/libc.so)" /usr/lib/libc.so.6

ENV PATH="${PATH}:/opt/python/cp311-cp311/bin:/root/.cargo/bin"
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

RUN pip install maturin \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.83.0

WORKDIR /usr/src/pyperscan

CMD [ "maturin", "build", "-r", "-o", "dist", "--compatibility", "musllinux_1_1", "-F", "vectorscan" ]
