[project]
name = "pyperscan"
authors = [
    {name = "László Vaskó", email = "1771332+vlaci@users.noreply.github.com"},
]
dependencies = []
requires-python = ">=3.8"
dynamic = [
    'description',
    'license',
    'readme',
    'version'
]

[project.urls]
repository = "https://github.com/vlaci/pyperscan"

[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.pdm.scripts]
venv = "pdm sync -d"
mypy = "mypy ."
ruff = "ruff ."
pytest = "python -m pytest tests"
clippy = "cargo clippy --all-targets -- --deny warnings"
all = { composite = ["clippy", "venv", "ruff", "mypy", "pytest"] }

[tool.pdm.dev-dependencies]
dev = [
    "black      ~= 23.3",
    "mypy       ~= 1.2",
    "pre-commit ~= 3.3",
]
test = [
  "pytest ~= 7.0.0",
]

[tool.isort]
profile = "black"
