name: Docs

on:
  push:
    branches:
      - main

    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/Docs.yml"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version-file: ".python-version"
      - run: |
          uv sync --no-install-project --group docs
          uv run mkdocs gh-deploy --force
