name: Docs

on:
  push:
    branches:
      - main

    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/Docs.yml"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: "3.10"
          cache: true
      - run: |
          pdm sync -d -G docs --no-self
          pdm run mkdocs gh-deploy --force
